### ISSUE TITLE
Feature Request: Custom PDF without modifying the source code

### ISSUE THREAD

**Issue by Zinoex** [Kiguli/IMPaCT#2]
Is it possible to add a `customPDF` without modifying the source code of IMPaCT? For context, I try to run an example with a custom PDF using the docker image and thus I have three options: move the file with `customPDF` into the source to override custom.cpp, copy it into the same path, or link directly from the example. 

If I copy or link it, then I getting a linker error since the function will be doubly defined.

If I instead move it, since I need to mount the examples folder to the host machine to access the results, then I will also remove the file from the host machine.

Do you have a proposal to solve this issue?

**Comment by Kiguli** [comment]
Hi Frederik, 

Thanks for your question, it sounds like you might be trying to run a large test suite in one shot so you don't want to change the file manually each time? When I was writing the code I didn't have this sort of use case in mind, only the single runs idea. You could certainly write a shell script that automatically changes specific lines of files you wish to run, thats how I have automated multiple runs with varying parameters in the past. A little cumbersome but it works. One option would be you can have multiple files with different names that are essentially copies of the `custom.cpp` file and then change the line `#include "custom.cpp"` inside `IMDP.cpp` to point to the new file.

 I imagine you might even be able to do this inside of each example file itself, then the line `#include "custom.cpp"` could perhaps be commented out altogether in `IMDP.cpp`. You'll need to make sure the files are added in the correct locations to be included. 

I think you could alternatively use `namespaces` where you update the file as:

```
namespace N1 {
    double newCustomPDF(double *x, size_t dim, void *params){}
}
```
Then you can call the function specific to this namespace using `N1::myFunction();` or something similar to that. You should then be able to include multiple files with the same function name defined but different namespaces and it should avoid linker errors.

Both solution sort of involve a shell script, unless you can include the file you want inside the example script itself. Afraid I haven't had time to try the solutions out myself, please let me know if either is suitable :)

Cheers,
Ben

**Comment by Kiguli** [comment]
A second option which takes a small amount of effort (and involve changing the source code as a one off) but is not particularly challenging would be to update the functions to accept the customPDF function as a second parameter when selecting NoiseType::CUSTOM. In fact, I have noticed the struct costcustom3Full includes customPDF (I forgot to delete it!) so this was originally intended before I changed it to the current approach as I believed it would be easier for users.

**Comment by Zinoex** [comment]
Thanks for the speedy reply, Ben! The use case is indeed a large suit of tests that I am running as part of a comparison :-)

I think a shell script to modify IMDP.cpp to remove `#include "custom.cpp"` (and instead include `extern customPDF;`?) would be a good temporary option.

For improving the interface of the toolbox, my opinion is that the better option is to include a second parameter when selecting `NoiseType::CUSTOM`. This way the toolbox is a self-contained and requires no modification :-)

**Comment by Kiguli** [comment]
Hi Frederik,

I believe I have now implemented the requested feature and you should be able to load the customPDF function via the extended command: 
``` 
void setCustomDistribution(double (*c)(double*, size_t, void*),size_t monte_carlo_samples);
``` 
which now takes two arguments. I also updated the customPDF example in the examples folder.

I am currently cleaning up the IMPaCT code and trying to add a couple new features. I have done some simple bug testing but not extensively yet, please let me know if you find any issues. I hope to start a tool manual as well when I have cleaned things up significantly.

Cheers,
Ben
